### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by Armagedon13** [GTQT/GTQTcore#34]
https://mclo.gs/D336PFC

**Comment by KeQingsocute520** [comment]
你加 GTFO了吗

**Comment by Armagedon13** [comment]
yes, but it crash with nomi labs in item registration

**Comment by Armagedon13** [comment]
[crash](https://mclo.gs/seAYHw6)
the [mod](https://www.curseforge.com/minecraft/mc-mods/nomi-labs) 
the idea of nomi labs is GroovyScript Helpers:
Allow replacing of GregTech CEu crafting recipes, with the recycling recipes and OreDictUnifier Data updating automatically
Allow refreshing of GregTech CEu recycling recipes at any time, allowing for these to be changed with GroovyScript's reload feature

**Comment by KeQingsocute520** [comment]
gtqtcore肯定是和nomilab不兼容的，gtqtcore是我自己的整合包模组，不可能去兼容其他附属
