### ISSUE TITLE
Hangs on startup

### ISSUE THREAD

**Issue by aking4125** [GTQT/GTQTcore#35]
Hello, After adding this mod to my pack, the game hangs on startup on the 5/7 stage. There is no crash, and the log stops. Do you have any ideas?

[debug.zip](https://github.com/user-attachments/files/17397499/debug.zip)

This mod seems to be required for [Pollution](https://legacy.curseforge.com/minecraft/mc-mods/pollution), however the [github ](https://github.com/GTQT/Pollution) link to that mod doesn't work.

[crash-2024-10-16_10.49.56-client.txt](https://github.com/user-attachments/files/17397678/crash-2024-10-16_10.49.56-client.txt)

There should be a dependency link to the mods on Curseforge to show that they require each other.

**Comment by KeQingsocute520** [comment]
这是我整合包的核心模组，不考虑其他包是否能使用

**Comment by aking4125** [comment]
> 这是我整合包的核心模组，不考虑其他包是否能使用

Yes. The core module itself is causing the crash. Not Pollution. That error is technically a separate issue. But understood.

**Comment by KeQingsocute520** [comment]
我不关心
