### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Ling-ye-Future** [GTQT/GTQTcore#47]
1、灵宝锭gt化配方
2、增生之种、蕴魔土配方略贵
3、一次性工具用途有些欠缺，例如制作形态谐振器时，在封包编码台上最多只能放一个一次性工具才能识别到配方
4、交换机与交换机之间是否能互传算力
5、魔导电池储量buff？

**Comment by KeQingsocute520** [comment]
上边两个你应该去pollution拉issue
至于4 5我会考虑的
